#!/usr/bin/env bash
set -e
trap 'error "$(printf "Command \`%s\` at $BASH_SOURCE:$LINENO failed with exit code $?" "$BASH_COMMAND")"' ERR

## find directory where this script is located following symlinks if necessary
readonly MDEV_DIR="$(
  cd "$(
    dirname "$(
      (readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}") \
        | sed -e "s#^../#$(dirname "$(dirname "${BASH_SOURCE[0]}")")/#"
    )"
  )" >/dev/null \
  && pwd
)"
readonly MDEV="$MDEV_DIR/$(basename ${BASH_SOURCE[0]})"


source "${MDEV_DIR}/bin/include/base.sh"

## parse first argument as command and determine validity
if (( "$#" )); then
  ## local project directory if running within one; don't fail if it can't be found
  if [[ -f "${MDEV_DIR}/bin/${1}" ]]; then
     COMMAND="${1}"
     shift
     if [[ "${1}" == "help" ]] || [[ "${1}" == "--help" ]]; then
       ${MDEV_DIR}/m help $COMMAND || exit $? && exit $?
     fi
     source "${MDEV_DIR}/bin/${COMMAND}";
  else
    echo "No command found"
  fi
else
  bold=$(tput bold)
  end=$(tput sgr0)

  echo -e  "\033[35m
   .__  __.   Welcome to          _
   |  \/  | __ _  __ _  ___ _ __ | |_ ___
   | |\/| |/ _\` |/ _\` |/ _ \ :_ \| __/   \\
   | |  | | ( | | (_| |  __/ | | | || ( ) |
   |_|  |_|\__,_|\__, |\___|_| |_|\__\___/
                 |___/   ${bold}DevBox${end}  v.1.0 ...
  \033[0m"
  echo "
  Run ${bold}mdev${end} [command] to execute commend
   or ${bold}mdev${end} help [command] to get help

 List of available commands:"
  for f in ${MDEV_DIR}/bin/* ; do
    if [ -f $f ]; then
      echo -e "    \033[32m$(basename $f)${end}"
    fi;
  done

fi

