#!/bin/bash

# https://wiki.corp.x.com/display/MTF/Installation
cd dev/tests/functional/
composer install
php utils/generate.php

#Magento 2 instance is installed properly:
php -r '(new PDO("mysql:host=db;dbname=magento", "root"))->exec("CREATE DATABASE IF NOT EXISTS magento_integration_tests;");'
#The Admin Account Sharing drop-down menu is set to Yes in the backend (Stores > Configuration > Advanced > Admin > Security);
php -r '(new PDO("mysql:host=db;dbname=magento", "root"))->exec("INSERT IGNORE INTO magento.core_config_data (scope, scope_id, path, value) VALUES (\"default\", 0, \"admin/security/admin_account_sharing\", \"1\")");'
#The Enable WYSIWYG Editor drop-down menu is set to Disabled Completely in the backend (Stores > Configuration > General> Content Management > WYSIWYG Options);
php -r '(new PDO("mysql:host=db;dbname=magento", "root"))->exec("INSERT IGNORE INTO magento.core_config_data (scope, scope_id, path, value) VALUES (\"default\", 0, \"cms/wysiwyg/enabled\", \"disabled\")");'
