#!/bin/bash

shopt -s extglob
dir=$(basename $(pwd))

ver=${1:-'ce'}
DB=${2:-$dir}
HOST_DB=${3:-localhost}
HOST=${4:-$dir.dev}

#mysql -uroot -e "DROP DATABASE IF EXISTS $DB; create database $DB;"
#sudo php5dismod -s cli xdebug

if [ -d .git ]; then
   git clean -dxf --exclude='.idea' --exclude=dev/tests/functional/etc/config.xml --exclude=dev/tests/functional/phpunit.xml --exclude=dev/tests/integration/etc/install-config-mysql.php
   git checkout composer.lock composer.json
fi

if [ $ver = 'ee' ] || [ $ver = 'b2b' ]; then
   cp -rlf ../magento2ee/!(.git|vendor|..|.) .
fi

if [ $ver = 'b2b' ]; then
   cp -rlf ../magento2b2b/!(.git|vendor|..|.) .
fi

composer install

bin/magento setup:install \
   --cleanup-database \
   --language=en_US \
   --timezone=Europe/Kiev \
   --currency=USD \
   --use-secure=0 \
   --use-secure-admin=0 \
   --admin-use-security-key=0 \
   --use-rewrites=0 \
   --backend-frontname=admin \
   --admin-lastname=Admin \
   --admin-firstname=Admin \
   --admin-email=magento@mailinator.com \
   --admin-user=admin \
   --admin-password=123123q \
   --base-url=http://$HOST/ \
   --db-name=$DB \
   --db-host=$HOST_DB


