version: "3.6"
services:
    varnish:
      image: eeacms/varnish
      ports:
        - "80:6081"
        - "6085:6085"
      depends_on:
        - webserver
      environment:
        BACKENDS: "webserver"
        BACKENDS_PORT: "80"
        DNS_ENABLED: "false"

        BACKENDS_PROBE_ENABLED: "false"
        BACKENDS_PROBE_INTERVAL: "3s"
        BACKENDS_PROBE_TIMEOUT: "1s"
        BACKENDS_PROBE_WINDOW: "3"
        BACKENDS_PROBE_THRESHOLD: "2"

        DASHBOARD_USER: "admin"
        DASHBOARD_PASSWORD: "admin"
        DASHBOARD_SERVERS: "mage.perf"