version: "3.6"
services:
    xhgui:
      build:
        context: .
        dockerfile: build/xhgui/Dockerfile
      hostname: xhgui.perf
      volumes:
        - ./etc/php/php.ini:/usr/local/etc/php/php.ini:ro
        - ./etc/php/apache.conf:/etc/apache2/sites-enabled/000-default.conf
